### ISSUE TITLE
Stream failed on webview

### ISSUE THREAD

**Issue by nadavkaner** [launchdarkly/js-client-sdk#129]
I'm using the sdk in both Chrome and Webview. and i have problems with the streaming in the Webview, the client doesn't get updates about flag changes. 
When i'm looking in the network tab it seems like the difference between the two is in the webview the request for `clientstream.launchdarkly.com/eval` failed.  
The error message is: Failed to load resource: The request timed out.
I tried to copy the cURL that both browsers is doing:
**Webview**
```
curl 'https://clientstream.launchdarkly.com/eval/5696d9987b1f40069c00002b/eyJpZCI6IjEiLCJrZXkiOiJhZG1pbkBpbnZpc2lvbmFwcC5jb20iLCJlbWFpbCI6ImFkbWluQGludmlzaW9uYXBwLmNvbSJ9' \
-XGET \
-H 'Pragma: no-cache' \
-H 'Accept: text/event-stream' \
-H 'Cache-Control: no-cache' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) WebView'
```
**Chrome**
```
curl 'https://clientstream.launchdarkly.com/eval/5696d9987b1f40069c00002b/eyJpZCI6IjEiLCJrZXkiOiJhZG1pbkBpbnZpc2lvbmFwcC5jb20iLCJlbWFpbCI6ImFkbWluQGludmlzaW9uYXBwLmNvbSJ9' \ 
-H 'Accept: text/event-stream' \ 
-H 'Cache-Control: no-cache' \ 
-H 'Origin: https://in-v7.local.invision.works' \
-H 'Referer: https://in-v7.local.invision.works/dsm/in-vision/sample-library/folder/colors/5bed2d414871e90018cff284' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' --compressed
```

The difference is in the origin and referer headers that Chrome added, I don't know if it's the problem but that's the best i can get.
The workaround that i found is to unregister and register again every couple of seconds which connect again to the stream i guess :)

Thanks for the help

**Comment by eli-darkly** [comment]
Hi. Sorry you're having difficulty. I don't think we've had a report like this before, so I'll have to think about how to go about diagnosing it.

Here's a question: when you looked at the network requests from the browser, did you by any chance see an `OPTIONS` request for the same URL, prior to the `GET` request? Normally there would not be one, but if there is one, that would be a clue.

**Comment by eli-darkly** [comment]
Also, there are a couple of different things called Webview; could you clarify which one you mean?

**Comment by nadavkaner** [comment]
About the first question, there is not an `OPTIONS` request before.
About the Webview, I'm working on sketch plugin, I'm not sure about that but i think it's a Webview of Webkit.
It can be a problem to do the workaround that i mentioned earlier? In addition, I'm not really sure why this workaround resolve the issue, i saw in the code that you reconnect to the stream, maybe this what cause to get fresh falg values?

**Comment by nadavkaner** [comment]
I thought maybe the problem is CORS problem, why the event stream doesn't support the withCredentials options like mention here: https://www.html5rocks.com/en/tutorials/cors/#toc-withcredentials. you think Is it possible to be the cause to the problem?

**Comment by eli-darkly** [comment]
Thanks for doing the detective work!

We actually do send a little bit of "heartbeat" data at regular intervals for basically this reason. However, we only do it once every three minutes. The streaming client in the server-side SDKs is set to time out after five minutes of inactivity. In JavaScript, we use the browser's built-in EventSource class to manage the streaming connection, and as far as we were able to determine, none of the browser implementations of EventSource had any timeout at all. But it seems that that's no longer true.

Anyway - it might be possible to work around this by using a polyfill to replace the built-in EventSource, just as people often do to provide EventSource support in browsers that don't have it. One popular package of this kind is [event-source-polyfill](https://github.com/Yaffle/EventSource). You would need to make sure that the polyfill script gets loaded before anything else - although you might actually need to add a little script before that, to set `window.EventSource` to `undefined` (since the polyfill might not install itself if it sees that there is already a built-in EventSource). You will also want to make sure you're using at least version 2.7.5 of our SDK, which has some logic for telling `event-source-polyfill` (or similar packages) to set the timeout to 5 minutes.

I think this workaround is worth a try. Please let me know if you're able to test it or if you have any questions about what I've said.

**Comment by louis-launchdarkly** [comment]
Closing this issue as we have not heard back from the requested since Jan 2019.
