### ISSUE TITLE
% rollouts on anonymous users and ld:$anonUserId

### ISSUE THREAD

**Issue by ohsabry** [launchdarkly/js-client-sdk#191]
Hey there,

We are using `launchdarkly-js-client-sdk` and want to use launchdarkly to control what page a non-logged in user sees with a feature flag.

Based on [these docs](https://docs.launchdarkly.com/docs/anonymous-users), I could do something like this to generate my own anonymous IDs and persist them somewhere like LocalStorage, which would be straightforward.

I was going to do this but I noticed that the sdk writes this key to localstorage `ld:$anonUserId` with a random identifier.

Is there a way to do % rollout based on this sdk-generated key while keeping users anonymous, or should I proceed with genrerating my own keys for anonymous users?

**Comment by bwoskow-ld** [comment]
Hi @ohsabry,

As you pointed out, you can do percentage rollouts with anonymous users as long as each user is specified with a consistent identifier.  By using consistent identifiers, each user will consistently receive a single variation as determined by your rollout.

If you're using version 2.10 or later of the SDK, the SDK can generate and store (in local storage) these identifiers for you. See [this documentation](https://docs.launchdarkly.com/docs/js-sdk-reference#section-anonymous-users) for details. The `anonymous: true` attribute will ensure that these users stay anonymous, and their keys will be generated automatically.

If you're using an older version of the SDK, you'll have to generate and persist the identifiers yourself.

Let me know if that fully answered your question!

Cheers,
Ben

**Comment by ohsabry** [comment]
@bwoskow-ld thanks for the answer! just to make sure I understand you right, if I use 2.10 or later and use the `anonymous: true` option, I'll be able to do % rollouts on those users?

**Comment by eli-darkly** [comment]
Yes - to be clear, you would do this by _not_ generating your own random key, and not specifying any other key, but instead declaring the user object as just `{ anonymous: true }`. In that case, the SDK (as of version 2.10) will generate a UUID key— since LaunchDarkly does require every user to have some kind of key. Percentage rollouts, since they are based on a hash of the user properties including the key, will treat each of these users separately. The JS SDK caches the generated key in local storage so that if the same person accesses your site from the same browser, they will get the same feature flags; but the user is still anonymous in the sense that this key does not show up on your LD dashboard and is not associated with any kind of identifying information. It's just the equivalent of a cookie that is correlated with a certain feature flag state.

**Comment by bwoskow-ld** [comment]
It sounds like we've answered your question, @ohsabry . I'm going to close this ticket now, but feel free to comment and re-open it if you'd like further clarification.
