### ISSUE TITLE
QuotaExceededError

### ISSUE THREAD

**Issue by comatory** [launchdarkly/js-client-sdk#211]
**Is this a support request?**

No

**Describe the bug**

The bug does not manifest in UI and I don't think it crashes application code but it is a warning so it should probably be dealt with.

**To reproduce**

Not sure :( My code is private and I'm getting this error via Sentry.

**Expected behavior**

No error.

**Logs**

```
Failed to execute 'setItem' on 'Storage': Setting the value of 'ld:5ea84316c2a9420aa83ea8d1:$diagnostics' exceeded the quota.
````

```
/<anonymous> in new Promise
./node_modules/launchdarkly-js-client-sdk/dist/ldclient.es.js in set at line 1:33694
{snip} n){n(window.localStorage.getItem(e))}))},set:function(e,n){return new Promise((function(t){window.localStorage.setItem(e,n),t()}))},clear:fu {snip}
```

**SDK version**
`2.17.3`

**Language version, developer tools**

Javascript error via V8 runtime.

**OS/platform**

Chrome Version: 81.0.4044 on MacOS 10.15.4

**Additional context**

-

**Comment by eli-darkly** [comment]
This happens if the SDK is using browser local storage for caching (due to setting "bootstrap: 'localstorage'" in the configuration), and the browser has accumulated more than 5 megabytes of local storage data for the same hostname so it is not allowing any more to be stored. Are you also using local storage for other purposes in your front-end code, or is it possible that the SDK has accumulated a large amount of cached data because you've run it with many different users?

**Comment by comatory** [comment]
Yes that is very probable. My app stores a lot of data in local storage so the possibility of no more space is high. Thanks.
