### ISSUE TITLE
Angular service worker + LaunchDarkly not working together

### ISSUE THREAD

**Issue by VladislavSemenets** [launchdarkly/js-client-sdk#221]
**Description**

I've got a fairly large Angular 8 project where we've recently added the built in service worker. Now I'd also like to implement feature toggling through LaunchDarkly.

Using their client-side JS SDK, the service worker appears to modify the requests (using fetch I believe), specifically adding cache-control to Access-Control-Request-Headers, but since this header is not present on the response from LaunchDarkly, the browser refuses to accept it, both breaking the integration and resulting in an infinite loop of connection attempts.

How can I configure my ngsw-config.json to leave these external requests alone? Or should this issue be fixed on the LaunchDarkly side (either through the SDK or in the LD project settings)?

Disabling the service worker fixes the issue, so I'm certain that's where it originates.

[Original issue on StackOverflow](https://stackoverflow.com/questions/59154529/angular-service-worker-launchdarkly-not-working-together)

**Comment by bwoskow-ld** [comment]
Hi @VladislavSemenets ,

Thanks for reaching out. I confirmed that `Cache-Control` is not included in the `Access-Control-Request-Headers` value for responses coming from LaunchDarkly, however, that's because it is on the [CORS header safelist](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header) by default.

I'm not familiar with the details of Angular development as we don't use it internally, but from googling your problem I came across [this question](https://stackoverflow.com/questions/51659368/how-to-disable-preflight-cache-control-headers-for-angular-service-worker-when) which may provide a sufficient workaround for you in your `ngsw-config.json` file. Besides that, I recommend that you continue to look for an Angular-specific solution to the problem.

Cheers,
Ben
