### ISSUE TITLE
Experimentation docs reference a version that is unreleased

### ISSUE THREAD

**Issue by th3fallen** [launchdarkly/js-client-sdk#263]
https://docs.launchdarkly.com/home/about-experimentation?site=launchDarkly#prerequisites says you need 2.6 of this library but the latest is 2.24....

**Comment by eli-darkly** [comment]
2.24 is a greater version than 2.6— the minor version is 24. Versions are sorted by their numeric components, not as alphanumeric strings.

Version 2.6 was released in 2018, as noted in the changelog. I think the confusion here is due to the fact that the NPM package name was changed in 2019 from `ldclient-js` to `launchdarkly-js-client-sdk`, so you're correct that there's no such thing as a version 2.6.0 of `launchdarkly-js-client-sdk`. But there was a version 2.6.0 of the LaunchDarkly JavaScript SDK, using the package name that was current at that time, and the documentation is correct to say that you need a version that is _at least_ 2.6.0. That specific version would no longer be supported in any case since it is four years old.
